import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/output.css" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <div>
          <div className="mt-3 absolute">
            <sup>1/1</sup>
            <h1 className="text-6xl font-light font-underline">
              hola i'm david &#x2198;
            </h1>
            <div className="mt-3"></div>
            <span className=" text-slate-600">
              engineer , chess enthuasiat , cs graduate
            </span>
          </div>
          <img
            src="/me.jpeg"
            className="w-3/5 float-right rounded-full border"
          ></img>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
