import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import Dialog from "./components/Dialog";

const lastOnline = (timestamp) => {
  var date = new Date(timestamp * 1000);
  var diff = Math.abs(new Date() - date);
  return new Date(diff).getMinutes();
};

export default function Home() {
  useEffect(() => {
    if (typeof window !== "undefined") {
      const url = window.location.href;

      console.log(url)
    }
  });

  return (
    <div className={`${styles.container} bg-neutral-100`}>
      <Head>
        <title>david yeböah , swe | home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/output.css" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <div className="">
          <div className="mt-28 pt-12 absolute">
            <sup className="">
              <sup>1</sup>
              <span className="buntu">/</span>
              <sub className="mx-1">1</sub>
            </sup>
            <h1 className="md:text-6xl font-light">hola i'm david &#x2198;</h1>
            <div className="mt-3"></div>
            <span className="text-slate-600">
              <Dialog title={"engineer"} color={"bg-blue-100"}>
                david yeböah is a{" "}
                <span className="bg-blue-100">
                  software developer at ibm in durham
                </span>
                , working on making a productive environment for ibm employees
                worldwide and to also deliver the future of IT.
              </Dialog>
              <span className="buntu"> / </span>
              <Dialog title="chess player" color={"bg-red-200"}>
                <img
                  class="float-left w-24 rounded m-1"
                  src="https://images.chesscomfiles.com/uploads/v1/user/10869942.a0d3097c.200x200o.7e5e8784f865.jpeg"
                ></img>
                <span className="m">
                  davey3b (1099){" "}
                  <img src="/us.svg" className="w-5 inline"></img>
                  <br></br>
                  Last online : {lastOnline(1658285651)} mins ago Followers : 13{" "}
                </span>
                <p className="mt-10">
                  <span className="bg-red-200">
                    An avid player of <span className="bdr">3</span> min chess
                    blitz.
                  </span>{" "}
                  Feel free to challenge him when you're feeling worthy
                </p>
              </Dialog>
              <span className="buntu"> / </span>
              <Dialog title="cs graduate" color={"bg-lime-200"}>
                he is a{" "}
                <span className="bg-lime-200">
                  cs graduate from suny oswego with minor in mathematics.
                </span>{" "}
                he's also currently enrolled at usc for ms in computer science
                and aims to graduate in 2023
              </Dialog>
            </span>
          </div>
          <img
            src="/me.jpeg"
            className="hidden md:block w-3/5 float-right rounded-full border"
          ></img>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      <style jsx>{`
        .buntu {
          font-family: "IBM 3270 Semi-Condensed";
        }
      `}</style>
    </div>
  );
}
