import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";

const lastOnline = (timestamp) => {
  var date = new Date(timestamp * 1000);
  var diff = Math.abs(new Date() - date);
  return new Date(diff).getMinutes();
};

export default function Home() {
  const [showEngineer, setEngineer] = useState(false);
  const [showChess, setChess] = useState(false);
  const [showGraduate, setGraduate] = useState(false);

  return (
    <div className={`${styles.container} bg-gray-100`}>
      <Head>
        <title>david yeböah , swe | home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/output.css" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <div>
          <div className="mt-28 absolute">
            <sup>1/1</sup>
            <h1 className="text-6xl font-light font-underline">
              hola i'm david &#x2198;
            </h1>
            <div className="mt-3"></div>
            <span className=" text-slate-600">
              <div className="inline-block relative">
                <span className="" onMouseOver={() => setEngineer(true)}>
                  engineer
                </span>
                <div
                  className={`drop-content absolute bg-white ${
                    !showEngineer ? "hidden" : ""
                  }`}
                  onMouseLeave={() => setEngineer(false)}
                >
                  <span className="underline">engineer</span>
                  <p className="buntu mt-2">
                    david yeböah is a software developer at ibm in durham,
                    working on making a productive environment for ibm employees
                    worldwide and to also deliver the future of IT.
                  </p>
                </div>
              </div>
              {" "} , {" "}
              <div className="inline-block relative">
                <span className="" onMouseOver={() => setChess(true)}>
                  chess player
                </span>
                <div
                  className={`drop-content absolute bg-white ${
                    !showChess ? "hidden" : ""
                  }`}
                  onMouseLeave={() => setChess(false)}
                >
                  <span className="underline">chess player</span>
                  <div className="buntu mt-2">
                    <img
                      class="float-left w-24 rounded m-1"
                      src="https://images.chesscomfiles.com/uploads/v1/user/10869942.a0d3097c.200x200o.7e5e8784f865.jpeg"
                    ></img>
                    <span className="m">
                      davey3b (1099) {" "}
                      <img src="/us.svg" className="w-5 inline"></img>
                      <br></br>
                      Last online : {lastOnline(1658285651)} mins ago Followers
                      : 13{" "}
                    </span>
                    <p className="mt-9">
                      An avid player of 3 min chess blitz. Feel free to
                      challenge him when you're feeling worthy
                    </p>
                  </div>
                </div>
              </div>
              {" "} , {" "}
              <div className="inline-block relative">
                <span className="" onMouseOver={() => setGraduate(true)}>
                  cs graduate
                </span>
                <div
                  className={`drop-content absolute bg-white ${
                    !showGraduate ? "hidden" : ""
                  }`}
                  onMouseLeave={() => setGraduate(false)}
                >
                  <span className="underline">cs graduate</span>
                  <p className="buntu mt-2">
                    david is also a cs graduate from suny oswego with minor in
                    mathematics. he's also currently enrolled at usc for ms in
                    computer science and aims to graduate in 2023
                  </p>
                </div>
              </div>
            </span>
          </div>
          <img
            src="/me.jpeg"
            className="w-3/5 float-right rounded-full border"
          ></img>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <style jsx>{`
        .drop-content {
          z-index: 1;
          border: 0.2vh solid black;
          font-size: 1.6vh;
          padding: 0.8vh;
          padding-right: 1vh;
          width: 36vh;
          top: 0;
        }

        .buntu {
          font-family: "Ubuntu mono";
        }
      `}</style>
    </div>
  );
}
